[package]
name = "SeaPad"
version = "1.0.0"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui", subdir = "crates/sui-framework/packages/sui-framework", rev = "testnet" }

[addresses]
seapad =  "0x00"
sui =  "0x02"


# staking admin
treasury_admin = "0xcd01f6033890993524f632f287b0b6d568fe9c9f78e3839b16ec3814955318af"
stake_emergency_admin = "0xcd01f6033890993524f632f287b0b6d568fe9c9f78e3839b16ec3814955318af"

# staking test addresses.
treasury = "0x13"
emergency = "0x14"
alice = "0x15"
bob = "0x16"