[package]
name = "ME_Launch_V1"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet" }
coin_test_one = { git = "https://github.com/Tricky4/coin_test_lp.git", rev = "main", override = true }

[addresses]
ME_Launch_V1 = "0x0"
sui = "0x2"